# Generated by Django 2.2.4 on 2019-09-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20190902_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, unique=True),
        ),
    ]
