# Generated by Django 2.2.4 on 2019-09-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20190918_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='deletion_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='image_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='notes_mark',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='text_mark',
            field=models.BooleanField(default=False),
        ),
    ]
