# Generated by Django 2.2.4 on 2019-10-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20190921_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('categories', models.ManyToManyField(related_name='files_m2m', to='content.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
