# Generated by Django 2.2.4 on 2019-10-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to='products/files/'),
            preserve_default=False,
        ),
    ]
