# Generated by Django 2.2.4 on 2019-09-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='shown_in_footer',
            new_name='shown_in_footer_other',
        ),
    ]
